### ISSUE TITLE
Support --open flag on Linux

### ISSUE THREAD

**Issue by techygrrrl** [techygrrrl/sf6vid#4]

**Comment by QuLogic** [comment]
You can probably get by with using `xdg-open` for this.

**Comment by techygrrrl** [comment]
> You can probably get by with using `xdg-open` for this.

Thanks @QuLogic! I gave it a try and it works on WSL on Windows, so I'm assuming it'll work on real Linux.

**Comment by techygrrrl** [comment]
closed by e610b9316f4b9de309a7c3b0076957090f572a65
